version: '3'
services:
  db:
    container_name : digitalBank
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: DigitalBank
    ports:
      - 3308:3306
    volumes:
      - dbdata:/var/lib/mysql
volumes:
    dbdata:
